/* autogenerated by Processing revision 1276 on 2021-10-09 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import processing.sound.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class Timer_Project extends PApplet {


SoundFile alert;
Timer timer;
Button restartButton;
Button startButton;
Timer restTimer;
Button plusOne;
Button minusOne;
Button plusFive;
Button minusFive;
Button select;
int interval;
int workout;
int rest;
boolean mouseClicked = false;
int editingWorkout;
enum ApplicationState{
  workoutState,
  restState,
  menuState
}
ApplicationState currentState = ApplicationState.menuState;
 public void setup(){
  alert = new SoundFile(this,"beep.wav");
  editingWorkout = 0;
  /* size commented out by preprocessor */;
  timer = new Timer();
  restTimer = new Timer();
  restartButton = new Button(width/2,600,100,50,"Restart");
  startButton = new Button(width/2,600,100,50,"Start");
  timer.setInterval(workout);
  restTimer.setInterval(rest);
  interval = 0;
  plusOne = new Button(width/2+150,400,100,50,"+1");
  minusOne = new Button(width/2-150,400,100,50,"-1");
  plusFive = new Button(width/2+300,400,100,50,"+5");
  minusFive = new Button(width/2-300,400,100,50,"-5");
  select = new Button(width/2,400,100,50,"Switch");
}
 public void draw(){
  
  //println(timer.secondsLeft());
  //background(255);
  //text(timer.secondsLeft(),width/2,height/2);
  //if(timer.alert() == true){
  //  background(0);
  //}
  //restartButton.show();
  //if(restartButton.checkClick() == true){
  //  background(255,0,0);
  //}
  background(255);
  switch(currentState){
    case menuState:
      startButton.show();
      plusOne.show();
      minusOne.show();
      plusFive.show();
      minusFive.show();
      select.show();
      if(select.checkClick()==true){
        editingWorkout++;
      }
      if(editingWorkout%3 == 0){
        text("Workout Timer",width/2,100);
        text(workout,width/2,200);
        if(plusOne.checkClick() == true){
           workout = workout+1;
        }
        if(minusOne.checkClick() == true){
           workout = workout-1;
           if(workout<0){
             workout = 0;
           }
        }
        if(plusFive.checkClick() == true){
           workout = workout+5;
        }
        if(minusFive.checkClick() == true){
           workout = workout-5;
           if(workout<0){
             workout = 0;
           }
        }
      }
      if(editingWorkout%3 == 1){
        text("Rest Timer",width/2,100);
        text(rest,width/2,200);
        if(plusOne.checkClick() == true){
          rest = rest+1;
        }
        if(minusOne.checkClick() == true){
          rest = rest-1;
          if(workout<0){
             workout = 0;
           }
        }
        if(plusFive.checkClick() == true){
          rest = rest+5;
        }
        if(minusFive.checkClick() == true){
          rest = rest-5;
          if(workout<0){
             workout = 0;
           }
        }
      }
      if(editingWorkout%3 ==2){
        text("Workout Intervals",width/2,100);
        text(interval,width/2,200);
        if(plusOne.checkClick() == true){
          interval = interval+1;
        }
        if(minusOne.checkClick() == true){
          interval = interval-1;
          if(interval<0){
             interval = 0;
           }
        }
        if(plusFive.checkClick() == true){
          interval = interval+5;
        }
        if(minusFive.checkClick() == true){
          interval = interval-5;
          if(interval<0){
             interval = 0;
           }
        }
      }
      if(startButton.checkClick() == true){
        currentState = ApplicationState.workoutState;
        timer.setTimeStamp();
        timer.setInterval(workout);
        restTimer.setInterval(rest);
      }
      break;
     case workoutState:
       
       text(timer.secondsLeft(),width/2,height/2);
       if(timer.secondsLeft() == 1 && alert.isPlaying() == false){
          alert.play();
        } 
       if(timer.secondsLeft() == 0){
        
         interval = interval - 1;
         if(interval == 0){
          currentState = ApplicationState.menuState;
        }
        else{
          restTimer.setTimeStamp();
          currentState = ApplicationState.restState;
        }
       }
       break;
      case restState:
       
        text(restTimer.secondsLeft(),width/2,height/2);
        if(restTimer.secondsLeft() == 1 && alert.isPlaying() == false){
          alert.play();
        }  
        if(restTimer.secondsLeft() == 0){
         
          timer.setTimeStamp();
          currentState = ApplicationState.workoutState;
        }
      
  }
  mouseClicked = false;
}
 public void mouseClicked(){
  mouseClicked = true;
}
class Button{
    float x,y,w,h;
    String text;
  public Button(float x, float y, float w, float h, String text){
       this.x = x;
       this.y = y;
       this.w = w;
       this.h = h;
       this.text = text;
  }
  public void show(){
    fill(255);
    rect(x-w/2,y-h/2,w,h);
    textSize(32);
    fill(0);
    textAlign(CENTER,CENTER);
    text(text,x,y);
  }
  public boolean checkClick(){
    if(mouseClicked == true && x-w/2<mouseX&& mouseX<x+w/2&&y-h/2<mouseY&&mouseY<y+h/2){
      return(true);
    }
    else{
      return(false);
    }
  }  
}

class Timer{
  int timeStamp;
  int interval;
  
  public Timer(){
    timeStamp = 0;
    interval = 0;
    
    
  }
  public void setInterval(int seconds ){
    interval = seconds*1000;
  }
  public void setTimeStamp(){
    timeStamp = millis();
  }
  public boolean alert(){
    if(timeStamp+interval<millis()){
      return(true);
     
    }
    else{
      return(false);
    }
  }
  public int secondsLeft(){
    return((timeStamp+interval-millis())/1000+1);
  }
}


  public void settings() { size(displayWidth, displayHeight); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "Timer_Project" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
